name: Update PR Template with JIRA Link

on:
    pull_request:
        types: [opened, reopened]

jobs:
    update-pr:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            repository-projects: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Get branch name and extract JIRA ID
              id: jira_id
              run: |
                  # Get the branch name from the environment
                  BRANCH_NAME=$(echo "${{ github.head_ref }}")

                  # Extract JIRA ID in the form DEV-XXXXX
                  JIRA_ID=$(echo "$BRANCH_NAME" | grep -oP 'DEV-\d+')

                  # Fail if no JIRA ID found
                  if [ -z "$JIRA_ID" ]; then
                    echo "No JIRA ID found in the branch name. Exiting."
                    exit 1
                  fi

                  # Print and set the JIRA ID
                  echo "JIRA ID: $JIRA_ID"
                  echo "jira_id=$JIRA_ID" >> $GITHUB_OUTPUT

            - name: Create JIRA link
              id: create_link
              run: |
                  # Using the JIRA ID from previous step to create a JIRA link
                  JIRA_ID="${{ steps.jira_id.outputs.jira_id }}"
                  JIRA_URL="https://your-jira-instance.com/browse/$JIRA_ID"

                  echo "JIRA Link: $JIRA_URL"
                  echo "jira_url=$JIRA_URL" >> $GITHUB_OUTPUT

            - name: Update PR description with JIRA link using GitHub CLI
              run: |
                  # Get the pull request number
                  PR_NUMBER="${{ github.event.pull_request.number }}"

                  # JIRA link generated from previous steps
                  JIRA_URL="${{ steps.create_link.outputs.jira_url }}"

                  # Get the current pull request body
                  PR_BODY=$(gh pr view $PR_NUMBER --json body --jq ".body")

                  # Replace the placeholder 'JIRA_LINK' with the actual JIRA link
                  UPDATED_BODY="# $JIRA_URL<br>something else<br>$PR_BODY"

                  # Update the pull request with the modified body
                  gh pr edit $PR_NUMBER --body "$UPDATED_BODY"
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
